config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations' }

  resources :users do
    resources :ceus
  end

  resources :ceus do
    resources :notes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ceu.rb
class Ceu < ActiveRecord::Base
    has_many :notes
    has_many :users, through: :notes

    scope :most_recent, -> { order(date: :desc) }

    validates :title, :date, :location, :duration, :certificate, presence: true

    def last_modified
      updated_at.localtime.strftime("%m/%d/%Y at %I:%M %p")
    end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :ceu

  accepts_nested_attributes_for :user, reject_if: :all_blank

  def self.most_recent
    order(created_at: :desc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

    validates :name, :email, presence: true, uniqueness: true

    has_many :notes
    has_many :ceus, through: :notes

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.name = auth.info.name
            user.password = Devise.friendly_token[0, 20]
        end
    end

    def last_login
        last_sign_in_at.localtime.strftime('%m/%d/%Y at %I:%M %p')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || user_path(current_user) #need to change this?
  end

end

app/controllers/ceus_controller.rb
class CeusController < ApplicationController
  def index
    if params[:user_id].to_i == current_user.id
      @ceus = current_user.ceus
      respond_to do |format|
        format.json {render json: @ceus}
        format.html {render :index}
      end
    else
      flash[:error] = "You can only access your own CEUs."
      redirect_to :root
    end
  end

  def new
    current_user = User.find_by(id: params[:user_id])
    @ceu = current_user.ceus.build
  end

  def create
    @ceu = current_user.ceus.create(ceu_params)
    if @ceu.save
      # flash[:success] = "CEU successfully created!"
      respond_to do |format|
        format.json {render json: @ceu, status: 201}
      end
    else
      # flash[:error] = "Please fill in all fields."
      render :new
    end
  end

  def show
    params[:user_id].to_i == current_user.id
    @ceu = current_user.ceus.find(params[:id])
    @note = Note.new
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @ceu}
    end
  end

  def edit
    if params[:user_id]
      current_user = User.find_by(id: params[:user_id])
      @ceu = current_user.ceus.find_by(id: params[:id])
      render :edit
    else
      @ceu = Ceu.find(params[:id])
    end
  end

  def update
    @ceu = Ceu.find(params[:id])
    @ceu.update(ceu_params)
    if @ceu.save
      respond_to do |format|
        format.json {render json: @ceu, status: 201}
      end
    else
      render :edit
    end
  end

  def destroy
    @ceu = current_user.ceus.find_by(id: params[:id])
    @ceu.destroy
    flash[:error] = "CEU successfully deleted."
    redirect_to user_ceus_path
  end

  private

  def ceu_params
    params.require(:ceu).permit(:title, :date, :duration, :location, :certificate)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    if params[:ceu_id]
      @notes = Ceu.find(params[:ceu_id]).notes
    else
      @notes = Note.all
    end
  end

  def create
    @ceu = current_user.ceus.find_by(id: params[:id])
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.ceu_id = params[:ceu_id]
    if @note.save
      flash[:success] = "Note successfully created!"
      redirect_to user_ceu_path(@note.user_id, @note.ceu_id)
    else
      flash[:error] = "Your note must have content"
      redirect_to user_ceu_path(@note.user_id, @note.ceu_id)
    end
  end

  def show
    if params[:ceu_id]
      ceu = current_user.ceus.find_by(id: params[:id])
      @note = current_user.notes.find_by(id: params[:id])
    else
      @note = Note.find(params[:id])
    end
  end

  def edit
    if params[:ceu_id]
      ceu = current_user.ceus.find_by(id: params[:id])
      @note = current_user.notes.find_by(id: params[:id])
      render :edit
    else
      @note = Note.find(params[:id])
    end
  end

  def update
    @note = Note.find(params[:id])
    @note.update(note_params)
    @note.save
    flash[:success] = "Note successfully updated."
    redirect_to user_ceu_path(@note.user_id, @note.ceu_id)
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:error] = "Note successfully deleted."
    redirect_to user_ceu_path(@note.user_id, @note.ceu_id)
  end

  private

  def note_params
    params.require(:note).permit(:content, :ceu_id, :user_id)
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    email_changed = @user.email != params[:user][:email]
    is_facebook_account = !@user.provider.blank?
    successfully_updated = if !is_facebook_account
      @user.update_with_password(update_params_with_password)
    else
      @user.update_without_password(update_params_without_password)
    end
    if successfully_updated
      sign_in @user, :bypass => true
      set_flash_message(:success, :updated) if is_navigational_format?
      redirect_to user_path(current_user)
    else
      render "edit"
    end
  end

  private

  def sign_up_params
      params.require(:user).permit(:name, :occupation, :email, :password, :password_confirmation)
  end

  def update_params_with_password
    params.require(:user).permit(:name, :occupation, :email, :password, :password_confirmation, :current_password)
  end

  def update_params_without_password
    params.require(:user).permit(:name, :occupation, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # before_action :set_user, only: [:show, :edit, :update]
  # after_action :verify_authorized

  def index
    if current_user.admin?
      @users = User.all
    else
      redirect_to :root
      flash[:error] = "You do not have admin access."
    end
  end

  def new

  end

  def show
    if params[:id].to_i == current_user.id || current_user.admin?
      @user = User.find(params[:id])
    else
      redirect_to :root
      flash[:error] = "Unauthorized Access"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ceus_helper.rb
module CeusHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ceus/_ceu.html.erb
<div class="card">
  <div class="card-block text-center">
    <h1 id="ceuTitle"><%= @ceu.title %></h1>
    <br/>
    <a href="#" class="js-next btn btn-outline-primary" data-id="<%=@ceu.id%>">Next CEU</a>
  </div>
  <%= render 'form' %>
  <ul class="list-group list-group-flush">
    <li class="list-group-item list-group-item-action" id="ceuLocation">Location: <%= @ceu.location %></li>
    <li class="list-group-item list-group-item-action" id="ceuDate">Date: <%= @ceu.date.strftime("%-m/%-d/%Y") %></li>
    <li class="list-group-item list-group-item-action" id="ceuDuration">Duration: <%= @ceu.duration %> minutes</li>
    <li class="list-group-item list-group-item-action" id="ceuCertificate">Certificate: <%= @ceu.certificate %></li>
  </ul>
  <div class="card-block text-xs-center editOptions">
    <%= link_to "Back", :back, class: 'btn btn-outline-info' %>
    <%= link_to "Edit CEU", edit_user_ceu_path, class: 'btn btn-outline-warning ceuEdit' %>
    <%= link_to "Delete CEU", user_ceu_path, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(function(){
    $('.edit_ceu').hide();
    $('.ceuEdit').on("click", function (e) {
      e.preventDefault();
      $('.list-group-flush, .editOptions, .js-next').fadeOut(500);
      setTimeout(function () {
        $('.edit_ceu').fadeIn(500);
      },500);
    });
    $('.edit_ceu').on('submit', function (e) {
      e.preventDefault();
      var values = $(this).serialize();
      $.ajax({
        type: 'put',
        url: this.action,
        data: values,
        dataType: 'json',
        success: function (data) {
          var editedCeu = new Ceu (data["title"], data["date"], data["location"], data["duration"], data["certificate"], data["id"]);
          $('.edit_ceu').fadeOut(1000);
          editedCeu.createHTML();
          setTimeout(function () {
            $('.list-group-flush, .editOptions, .js-next').fadeIn(1000);
          }, 500)
        }
      });
    });
    function Ceu(title, date, location, duration, certificate, id) {
      this.title = title;
      this.date = date,
      this.location = location;
      this.duration = duration;
      this.certificate = certificate;
      this.id = id;
    };

    Ceu.prototype.createHTML = function() {
      $('#ceuTitle').text(this.title);
      $('#ceuDate').text("Date: " + this.date);
      $('#ceuLocation').text("Location: " + this.location);
      $('#ceuDuration').text("Duration: " + this.duration + " minutes");
      $('#ceuCertificate').text("Certificate: " + this.certificate);
    };
  });
</script>

app/views/ceus/_form.html.erb
<%= form_for [current_user, @ceu] do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>

<div class="field">
  <span class="field"><i class="fa fa-info fa-fw"></i></span>
  <%= f.text_field :title, placeholder: "CEU Title" %>
</div>
<br>
<div class="field">
  <span class="field"><i class="fa fa-calendar-o fa-fw"></i></span>
  <%= f.date_field :date %>
</div>
<br>
<div class="field">
  <span class="field"><i class="fa fa-map-marker fa-fw"></i></span>
  <%= f.text_field :location, placeholder: "Location" %>
</div>
<br>
<div class="field">
  <span class="field"><i class="fa fa-clock-o fa-fw"></i></span>
  <%= f.number_field :duration, placeholder: "Duration in Minutes" %>
</div>
<br>
<div class="field">
  <span class="field"><i class="fa fa-trophy fa-fw"></i> Certificate Type:</span>
  <%= f.select :certificate, (["State", "National"]) %>
</div>
<br>
<div class="actions">
  <%= f.submit class: 'btn btn-outline-primary', value: 'Create CEU' %>
  <%= link_to "Back", :back, class: 'btn btn-outline-info' %>
</div>
<% end %>
<br>

app/views/ceus/edit.html.erb
<h1>Edit CEU:</h1>
<br>
<%= render 'form' %>
<br>

app/views/ceus/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
          <h1 class="display-4 card-header childrens-4 text-center">Your CEUs</h1>
          <div class="card-block">
              <p class="text-center"><%= link_to "New CEU", new_user_ceu_path(current_user), class: 'btn btn-outline-info' %> | <%= link_to "Show CEUs", user_ceus_path(current_user), class: "show-ceu btn btn-outline-info" %></p>
                <div class="card-block ceuDetails">
                  <ul>
                  </ul>
                </div>
          </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset='utf-8'>
  $(function() {
    //Show CEUs link
    $('.show-ceu').on('click', loadCeus);
    // callback function loadCeus to be called
    function loadCeus(e) {
      e.preventDefault();
      var result = $.getJSON(this.href);
      result.success(function(json){
        var $ul = $('div.ceuDetails ul')
        var user = <%= current_user.id %>
        $ul.html("")
        json.forEach(function(ceu) {
          var commentHtml = "<p class='lead'><a href='/users/" + user + "/ceus/" + ceu.id + "'>" + ceu.title + "</a></p>";
          $ul.append(commentHtml);
        });
      });
      // create a toggle for showing/hiding CEUs ... ?
          // add new class for button?
      // change text of button to say "Hide CEUs"
          // $(".show-ceu").text("Hide CEUs");
      // change text back to "Show CEUs" when they are hidden
          // $(".show-ceu").text("Show CEUS");
    };
  });
</script>

app/views/ceus/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "ceu_new/ceu_new" %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header display-4 childrens-4">New CEU</div>
          <div class="card-block">
            <%= render 'form' %>
          </div>
      </div>
    </div>
    <div class="col-xs-6" id="show">
      <h1 id="ceuDetails"></h1>
        <ul id="ceuInfo">
          <li id="ceuTitle"></li>
          <li id="ceuDate"></li>
          <li id="ceuLocation"></li>
          <li id="ceuDuration"></li>
          <li id="ceuCertificate"></li>
        </ul>
    </div>
  </div>
</div>

app/views/ceus/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 offset-md-3">
      <%= render 'ceu' %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(function(){
    var IDs = <%= current_user.ceu_ids %>
    $('.js-next').on('click', function(event){
      event.preventDefault();
      var nextId = IDs.shift();
      $.get("/ceus/" + nextId + ".json", function(data){
        var date = new Date(data["date"]);
        var result = (date.getMonth()+1) + '/' +(date.getDate()+1)  + '/' + date.getFullYear();
        $('#ceuTitle').text(data["title"]);
        $('#ceuLocation').text("Location: " + data["location"]);
        $('#ceuDate').text("Date: " + result);
        $('#ceuDuration').text("Duration: " + data["duration"] + " minutes");
        $('#ceuCertificate').text("Certificate: " + data["certificate"]);
        $('.js-next').attr("data-id", data["id"]);
      });
    });
// fadeOut after clicking "Next CEU", and fadeIn for next CEU
  });
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse childrens-1 bg-light">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/"><i class="fa fa-heartbeat fa-2x"></i></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "My Account", user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "My CEUs", user_ceus_path(current_user), class: 'nav-link' %></li>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "All Users", users_path, class: 'nav-link' %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, method: "delete", class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
          <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MyCEUs</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= yield :head %>
    </head>

    <body>
        <%= render 'layouts/navbar' %>
        <br>
        <div class="container">
          <%= render 'layouts/messages' %>
            <%= yield %>
        <nav class="navbar fixed-bottom navbar-light bg-faded">
            <span class="navbar-text">
                &copy; 2016 | Michael Casciato
            </span>
        </nav>
    </body>
</html>

app/views/notes/_edit.html.erb
<div class="card-block">
  <%= form_for [@note.ceu, @note]  do |f| %>
  <%= f.hidden_field :ceu_id %>
  <%= f.text_area :content, size: "50x6" %>
  <%= f.submit class: 'btn btn-outline-primary' %>
  <%= link_to "Delete Note", ceu_note_path, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %>
  <%= link_to "Back", :back, class: 'btn btn-outline-info' %>
  <% end %>
</div>

app/views/notes/_form.html.erb
<div class="card-block">
  <%= form_for [@ceu, @note] do |f| %>
  <%= f.hidden_field :ceu_id %>
  <%= f.text_area :content, size: "50x6" %>
  <%= f.submit class: 'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/notes/_notes.html.erb
<div class="card">
  <h1 class="card-header display-4 childrens-9 text-xs-center">Notes</h1>
  <div class="card-block">
    <table class="table table-hover">
      <tbody>
          <% @ceu.notes.most_recent.uniq.each do |note| %>
          <tr>
            <td id="noteContent" class="lead">
                <% if note.content.nil? %>
                <%= link_to "Click here to Edit your First Note!", edit_ceu_note_path(@ceu.id, note) %>
                <% else %>
                <%= link_to note.content, ceu_note_path(@ceu.id, note) %>
                <% end %>
            </td>
            <% end %>
          </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 offset-md-3">
      <div class="card">
        <h1 class="card-header display-4 childrens-4 text-xs-center">Edit Note</h1>
          <%= render 'edit' %>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<table class="table table-hover">
  <thead class="thead childrens-9">
    <tr>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
      <% current_user.notes.most_recent.uniq.each do |note| %>
      <tr>
        <td class="lead">
            <%= link_to note.content, edit_note_path(note) %>
        </td>
        <% end %>
      </tr>
  </tbody>
</table>

app/views/notes/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="display 4">New Note:</h1>
      <div class="col-xs-6 offset-md-3">
        <%= render 'form' %>
      </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 offset-md-3">
      <div class="card">
          <h1 class="card-header display-4 childrens-8">Note Content:</h1>
          <div class="card-block">
            <p class="lead"><%= @note.content %></p>
            <%= link_to "Back", :back, class: 'btn btn-outline-info' %>
            <%= link_to "Edit Note", edit_ceu_note_path, class: 'btn btn-outline-warning' %>
            <%= link_to "Delete Note", ceu_note_path, method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="card">
  <h3 class="card-header text-xs-center childrens-6">Your Information:</h3>
  <div class="card-block">
    <p class="card-text"><strong>Occupation:</strong> <%= @user.occupation %></p>
    <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
    <p class="card-text"><strong>Last Login:</strong> <%= @user.last_login %></p>
  </div>
  <div class="card-footer text-xs-center">
    <%= link_to "Edit User", edit_user_registration_path(@user), class: 'btn btn-outline-warning' %>
  </div>
</div>

app/views/users/_userceus.html.erb
<div class="card">
  <h1 class="card-header display-4 childrens-4 text-xs-center">Your CEUs:</h1>
  <div class="card-block">
    <% current_user.ceus.most_recent.uniq.each do |ceu| %>
     <p><%= link_to ceu.title, user_ceu_path(current_user, ceu) %></p>
    <% end %>
  </div>
  <div class="card-footer text-muted text-xs-center">
    <p>Most Recent First</p>
    <%= link_to "New CEU", new_user_ceu_path(current_user), class: 'btn btn-outline-info' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-6">
        <ul class="list-group" id="users">
          <% @users.each do |user| %>
            <li class="list-group-item"><%= link_to user.name, user_path(user) %></li>
          <% end %>
        </ul>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
      <div class="col-md-6">
          <% if current_user.admin? %>
            <h1>Hello, <%= @user.name %>!</h1>
            <p class="lead text-center">*ADMIN*</p>
      </div>
</div>
<div class="row">
      <div class="col-md-6">
        <%= render 'user_info' %>
      </div>
      <!-- <div class="col-xs-6">
        <h3 id="ceus" class="card-header childrens-4">Your CEUs</h3>
      </div> -->
      <% else %>
            <h1>Hello, <%= current_user.name %>!</h1>
                <div class="col-xs-6 offset-md-3">
                    <%= render 'user_info' %>
                </div>
     <% end %>
</div>

app/views/welcome/home.html.erb
<div class="jumbotron container-welcome">
  <h1 class="display-4">Welcome to MyCEUs</h1>
  <p class="lead">Choose an option above to get started tracking your <abbr title="Continuing Education Unit">CEUs</abbr>!</p>
  <hr class="my-4">
  <figure class="figure">
    <img src="http://blog.cincinnatichildrens.org/wp-content/uploads/2016/06/CCHMC-LOGO.png" class="figure-img img-fluid rounded" alt="Cincinnati Children's Hospital Medical Center">
    <br><br>
    <figcaption class="figure-caption">Image is the property of &copy <%= link_to "Cincinnati Children's Hospital Medical Center", ("https://www.cincinnatichildrens.org/") %>. All rights reserved.</figcaption>
  </figure>
</div>